version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/o0i6w3n6
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs-nginx-cicd .
      - docker tag ecs-nginx-cicd:latest public.ecr.aws/o0i6w3n6/ecs-nginx-cicd:latest   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/o0i6w3n6/ecs-nginx-cicd:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' public.ecr.aws/o0i6w3n6/ecs-nginx-cicd:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
